### ISSUE TITLE
Unable to connect to UDD from pgAdmin III

### ISSUE THREAD

**Issue by anton-khodak** [paulproteus/public-udd-mirror#10]
I am trying to connect to UDD using pgAdmin 1.22.0. I input all the credentials mentioned in the [docs](http://public-udd-mirror.xvm.mit.edu/), but I get this error
![_2017-01-13_12-02-06](https://cloud.githubusercontent.com/assets/10351924/21925940/533014f0-d988-11e6-8623-b2e7676f5730.png)
Logging in from `psql` console goes fine. What can I change to view the database from pgAdmin?

**Comment by mapreri** [comment]
You are connecting to the database `postgres` instead of the database `udd`.
Please try that and report back.

**Comment by anton-khodak** [comment]
Thank you, this resolved the issue, a silly one :)

**Comment by mapreri** [comment]
Glad it was so simple :)
