### ISSUE TITLE
Unable to connect to UDD

### ISSUE THREAD

**Issue by sebasfalcone** [paulproteus/public-udd-mirror#19]
Hello team! 

We are having problems connecting to the database, using the following command:
`psql "postgresql://udd-mirror:[udd-mirror@udd-mirror.debian.net](mailto:udd-mirror@udd-mirror.debian.net)/udd"`

This is the error messaege:
```
psql: error: connection to server at "udd-mirror.debian.net" (88.99.39.211), port 5432 failed: 
FATAL:  permission denied for database "udd"
DETAIL:  User does not have CONNECT privilege.
```

I think is has to do with these changes (see [changelog](https://udd-mirror.debian.net/logs/log.txt)):
```
2022-12-26 02:06:54 URL:https://udd.debian.org/dumps/udd.dump [2040928184/2040928184] -> "udd.dump" [1]
    ALTER DEFAULT PRIVILEGES FOR USER "udd" IN SCHEMA "public" GRANT SELECT ON TABLES TO "udd";
ALTER DEFAULT PRIVILEGES
    ALTER DEFAULT PRIVILEGES FOR USER "udd-mirror" IN SCHEMA "public" GRANT SELECT ON TABLES TO "udd-mirror";
ALTER DEFAULT PRIVILEGES
    ALTER DEFAULT PRIVILEGES FOR USER "public-udd-mirror" IN SCHEMA "public" GRANT SELECT ON TABLES TO "public-udd-mirror";
ALTER DEFAULT PRIVILEGES
CREATE EXTENSION debversion
CREATE EXTENSION
.
.
.
REVOKE CONNECT ON DATABASE udd FROM public
REVOKE
```

**Comment by werdahias** [comment]
+1 here, this causes cargo debstatus to fail because it can't connect to the database. I'd appreciate it if this could be resolved

**Comment by mapreri** [comment]
The endpoint didn't change, however yesterday I made a change that could be
related to this failure.

Thanks for reporting, I'll have a look soon.

**Comment by werdahias** [comment]
It looks like it is working again atm.

**Comment by sebasfalcone** [comment]
Hi! This error is once again present 

```
psql "postgresql://udd-mirror:udd-mirror@udd-mirror.debian.net/udd"
psql: error: connection to server at "udd-mirror.debian.net" (88.99.39.211), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

```

**Comment by mapreri** [comment]
different problem than last time (it seems the host was rebooted, but docker didn't come up for some reason…), but fixed nonetheless.

**Comment by sebasfalcone** [comment]
Thanks a lot
