### ISSUE TITLE
Create a debian.net domain for this

### ISSUE THREAD

**Issue by paulproteus** [paulproteus/public-udd-mirror#3]
Everyone loves debian.net domains.

**Comment by mapreri** [comment]
What about `udd-mirror.debian.net` ?
If we go down that route, shall we "hide" the current address public-udd-mirror.xvm.mit.edu, point it just on the homepage (i.e. "this service is running on public-udd-mirror.xvm.mit.edu"), or advertise both equally?

**Comment by mapreri** [comment]
(note that the reply to the above might also trigger a different setup of apache redirects from one address to the other)

**Comment by mapreri** [comment]
(Also note that if we go with 'udd-mirror.d.n', I'd like to also change the advertised username/password to `udd-mirror` too (from `public-udd-mirror`), just for consistency.  Of course both would be kept.)

**Comment by paulproteus** [comment]
+1 to this; thanks for taking care of it!

**Comment by paulproteus** [comment]
My hunch is it makes sense to advertise just one. Perhaps in a FAQ, list the old address and connection information and indicate that it will continue to work.

**Comment by mapreri** [comment]
> Perhaps in a FAQ, list the old address and connection information and indicate that it will continue to work.

Tracked in #11
